os: linux
language: minimal
services:
- docker
before_install:
- echo "Before install"
before_script:
- echo "Before script"
script:
- make build
- make test
- make stop
after_script:
- docker images
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "One can push to image dockerhub" ; fi
notifications:
  email: true
